### ISSUE TITLE
Misspelling of words

### ISSUE THREAD

**Issue by Geeksun2018** [jaemin-shin/FedBalancer#1]
![image](https://user-images.githubusercontent.com/42086593/195084332-07709129-4d58-4853-b3c7-3cf16038470a.png)
It should be timeout_decorator not timeout_decotrator.

**Comment by jaemin-shin** [comment]
Thank you very much for pointing this out! We have fixed the issue and recently released a patch of Pytorch version of FedBalancer :) 👍
