### ISSUE TITLE
About fb_p 

### ISSUE THREAD

**Issue by eardic** [jaemin-shin/FedBalancer#3]
Hi,

The parameter fb_p is used for OT in the paper but it is used for UT in this [codebase](https://github.com/jaemin-shin/FedBalancer/blob/1d187c88de9b5b43e28c988b2423e9f616c80610/models/fedbalancer.py#L117). Which is right? 

Thanks.

**Comment by jaemin-shin** [comment]
Hi! Thanks for taking a close look at our code. 

As you mentioned, fb_p is used for OT in the paper. However, at the time of code development, we were initially using fb_p for UT and (1 - fb_p) for OT. We later changed it to use fb_p for OT and (1 - fb_p) for UT when writing the paper.

While I should have fixed the entire usage of fb_p before releasing the code, we used a simple but fool fix to make it compliant with the paper and haven't changed it yet; 

if you look at line 156 of `utils/config.py`, we get the input of fb_p from config file and subtract it from 1.0 . Thus, we were able to use the code that we were using from the dev.

While the current code works as we designed, we will make sure to update this to reduce confusion. Thanks very much for pointing this out!
